import ICard from "@/interfaces/ICard";
import ICategoryCard from "@/interfaces/ICategoryCard";

export const ADS_UZ: ICard[] = [
  {
    images: [
      "/images/blackpods.png",
      "/images/phone.png",
      "/images/redpods.png",
    ],
    title: "totot",
    oldPrice: 1200,
    price: 1500,
    url: "product/wejfbhwiuefhuiwhfe",
    manifacturer: "JBL Quantum ONE",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: [
      "/images/blackpods.png",
      "/images/phone.png",
      "/images/redpods.png",
    ],
    title: "totot",
    oldPrice: 1200,
    price: 1500,
    url: "product/wejfbhwiuefhuiwhfe",
    manifacturer: "JBL Quantum ONE",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: [
      "/images/blackpods.png",
      "/images/phone.png",
      "/images/redpods.png",
    ],
    title: "totot",
    oldPrice: 1200,
    price: 1500,
    url: "product/wejfbhwiuefhuiwhfe",
    manifacturer: "JBL Quantum ONE",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
];

export const ADS_RU: ICard[] | Array<ICard> = [
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL JR",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JR 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
];

export const CARD_OBJ_UZ: ICard[] = [
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL JR",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JR 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
  {
    images: ["/images/product.png", "/images/product.png"],
    title: "JBL 310BT",
    oldPrice: 400,
    price: 300,
    url: "/product/some-id",
    manifacturer: "JBL Квантум ONE  ",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing eilt. Tempore libero, delectus aut sint dolore facere voluptatum quidem alias asperiores veniam non explicabo, sapiente dolor numquam corporis vero iste consectetur.",
  },
];
